spring:
  application:
    name: tracking-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/trackingdb
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: tracking-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ordertracking.*"

server:
  port: 8081

logging:
  level:
    com.ordertracking: DEBUG

kafka:
  topics:
    orders-events: orders.events

cache:
  ttl:
    order-tracking: 300
